# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'haveIg' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for haveIg
 pod 'AFNetworking'
  target 'haveIgTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'haveIgUITests' do
    # Pods for testing
  end

end
